services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_BACKEND_URL=http://172.19.0.4:8080/api/tasks
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - MONGO_CONN_STR=mongodb://root:rootpassword@mongodb:27017/todo?authSource=admin
    depends_on:
      - mongodb

  mongodb:
    build:
      context: ./db
      dockerfile: Dockerfile
    volumes:
      - mongodb-data:/data/db
volumes:
  mongodb-data:
